language: node_js
sudo: enabled
services:
    - mysql
node_js:
- "12.19.0"
before_install:
- sudo mysql -e 'CREATE USER 'admin'@'localhost' IDENTIFIED BY "modernwaitercpen321!";'
- sudo mysql -e 'GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';'
- sudo mysql -e 'FLUSH PRIVILEGES;'
- mysql -u admin -p MODERN_WAITER_DB < travis.sql
- modernwaitercpen321!\r
script: 
- echo 'Build is starting!'
- cd BackEnd
- npm test
